name: Frontend Web

on:
  push:
    branches:
      - main
    paths: 
      - frontend/web/**
  pull_request:
    branches:
      - main
    paths: 
      - frontend/web/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start job
        run: |
            aws amplify start-job \
            --app-id ${{ vars.AMPLIFY_PRODUCTION_APP_ID }} \
            --branch-name ${{ vars.AMPLIFY_PRODUCTION_BRANCH_NAME }} \
            --commit-id ${{ github.sha }} \
            --job-type RELEASE
